#!/usr/bin/env bash
# # This script will display numbers from 1 to 100 and,
# Will display "FizzBuzz" when the number is a multiple of 3 and 5
# Will displays "Fizz" when the number is a multiple of 3
# Will displays "Buzz" when the number is a multiple of 5
# Otherwise, will display the number
# All will be displayed in list format

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
